import type { SkillGroup } from "./types";

/**
 * Skill inventory transcribed from the source CV, grouped by discipline.
 * Group labels are translated in Dictionary.skillGroupLabels, keyed by `id`.
 */
export const skillGroups: SkillGroup[] = [
  {
    id: "game",
    tier: "core",
    skills: [
      "Unity (C#)",
      "Blender",
      "World Streaming / Chunk loading",
      "LOD",
      "Billboarding",
      "Texture Compression",
      "Auto-rigging",
      "Object Pooling",
    ],
  },
  {
    id: "mobile",
    tier: "core",
    skills: [
      "Flutter",
      "Dart",
      "Flutter Web",
      "Swift",
      "SwiftUI",
      "Riverpod",
      "Provider",
      "Flutter Hooks",
      "GoRouter",
      "Dio",
      "Deeplink",
      "Responsive UI",
    ],
  },
  {
    id: "backend",
    tier: "core",
    skills: [
      "Laravel",
      "PHP",
      "Kotlin",
      "Spring Boot",
      "ASP.NET MVC",
      "OpenAPI",
      "REST API",
      "Webhook",
      "Socket.IO",
      "WebRTC",
    ],
  },
  {
    id: "architecture",
    tier: "core",
    skills: [
      "Clean Architecture",
      "Service Locator",
      "Event Bus",
      "State Machine",
      "Strategy",
      "Interface Abstraction",
      "Singleton",
      "Dependency Injection (GetIt, Injectable)",
      "Multi-tenant",
    ],
  },
  {
    id: "frontend",
    tier: "working",
    skills: ["HTML", "CSS", "JavaScript", "jQuery", "WebView"],
  },
  {
    id: "data",
    tier: "working",
    skills: [
      "MySQL",
      "SQL",
      "Neo4j",
      "Query optimisation",
      "DB resource optimisation",
      "Secure Storage",
      "Shared Preferences",
    ],
  },
  {
    id: "cloud",
    tier: "working",
    skills: [
      "AWS (S3, CloudFront, EC2)",
      "Docker",
      "CI/CD",
      "Firebase",
      "Sentry",
      "DataDog",
      "OpenVPN",
    ],
  },
  {
    id: "quality",
    tier: "working",
    skills: [
      "Unit testing",
      "Feature testing",
      "Selenium",
      "Appium",
      "CodeceptJS",
      "Postman",
      "Bruno",
      "TestFlight",
      "Play Console",
      "App Store release",
    ],
  },
  {
    id: "integrations",
    tier: "working",
    skills: [
      "Zoom SDK",
      "Google Maps",
      "Coiney Payment",
      "In-App Purchase",
      "Apple Wallet",
      "Google Wallet",
      "Remote Lock API",
      "Temairazu",
      "Adjust SDK",
      "Social Auth (Apple, Facebook)",
      "Pasori Scanner",
      "Barcode / QR",
      "Biometrics (Face, Fingerprint)",
    ],
  },
  {
    id: "ai",
    tier: "working",
    skills: ["GitHub Copilot", "ChatGPT", "Gemini"],
  },
];
