import type { Project } from "../types";

/** Current and most recent engagements (2024/10 → present). */
export const projects2025Current: Project[] = [
  {
    id: "delivery-game",
    category: "game",
    period: "2025/12 — Current",
    isCurrent: true,
    teamSize: 3,
    tech: ["Unity", "C#", "Blender", "Clean Architecture", "Object Pooling", "World Streaming"],
  },
  {
    id: "learning-japanese-career",
    category: "mobile",
    period: "2025/05 — 2025/11",
    teamSize: 3,
    durationMonths: 6,
    tech: [
      "Flutter",
      "Dart",
      "Riverpod",
      "Flutter Hooks",
      "GetIt",
      "Injectable",
      "Dio",
      "GoRouter",
      "Firebase",
      "JustAudio",
      "VAD",
      "Adjust SDK",
    ],
  },
  {
    id: "learning-japanese",
    category: "mobile",
    period: "2024/10 — 2025/02",
    teamSize: 2,
    durationMonths: 4,
    tech: [
      "Flutter",
      "Dart",
      "Provider",
      "Flutter Hooks",
      "GetIt",
      "Injectable",
      "Dio",
      "GoRouter",
      "Firebase",
      "In-App Purchase",
      "JustAudio",
      "VAD",
    ],
  },
];
